DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    -- id INTEGER PRIMARY KEY AUTOINCREMENT,
    -- created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id TEXT PRIMARY KEY,
    original_url TEXT NOT NULL
);